"""First attempt

Revision ID: ebc591cc57f4
Revises: None
Create Date: 2020-10-11 15:22:32.626998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ebc591cc57f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("email_address", sa.String(length=120), nullable=False),
        sa.Column("secondary_email_address", sa.String(length=120), nullable=True),
        sa.Column("joining_date", sa.Date(), nullable=False),
        sa.Column("location_restriction", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_address"),
        sa.UniqueConstraint("secondary_email_address"),
    )
    op.create_table(
        "profession",
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("profession_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["profession_id"], ["profession.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skill",
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("core", sa.Boolean(), nullable=True),
        sa.Column("profession_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["profession_id"], ["profession.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posting",
        sa.Column("candidate_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("date_started", sa.Date(), nullable=True),
        sa.Column("date_ended", sa.Date(), nullable=True),
        sa.Column("rotation_number", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate.id"],),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assessment",
        sa.Column("posting_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("overall_mark", sa.String(length=56), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["posting_id"], ["posting.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skill_level",
        sa.Column("skill_id", sa.Integer(), nullable=True),
        sa.Column("assessment_id", sa.Integer(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessment.id"],),
        sa.ForeignKeyConstraint(["skill_id"], ["skill.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skill_level")
    op.drop_table("assessment")
    op.drop_table("posting")
    op.drop_table("skill")
    op.drop_table("role")
    op.drop_table("profession")
    op.drop_table("candidate")
    # ### end Alembic commands ###
